server:
  port: 5000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: BOOKING-SERVICE
              uri: "lb://BOOKING-SERVICE"
              predicates:
                - Path=/api/bookings/**

            - id: PAYMENT-SERVICE
              uri: "lb://PAYMENT-SERVICE"
              predicates:
                - Path=/api/payments/**

            - id: CATEGORY-SERVICE
              uri: "lb://CATEGORY-SERVICE"
              predicates:
                - Path=/api/categories/**

            - id: SALON-SERVICE
              uri: "lb://SALON-SERVICE"
              predicates:
                - Path=/api/salons/**,/api/admin/salons/**,/salons/**

            - id: OFFERING-SERVICE
              uri: "lb://BOOKING-SERVICE"
              predicates:
                - Path=/api/bookings/**

            - id: USER-SERVICE
              uri: "lb://USER-SERVICE"
              predicates:
                - Path=/api/users/**,/auth/**,/api/admin/users/**,/users/**

            - id: NOTIFICATION-SERVICE
              uri: "lb://NOTIFICATION-SERVICE"
              predicates:
                - Path=/api/notifications/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8080/realms/master/protocol/openid-connect/certs"
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"